apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: just-storage
  namespace: just-storage
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  ingressClassName: traefik
  rules:
    - host: storage.bk.glpx.pro
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: just-storage
                port:
                  number: 8080
